# -*- coding: utf-8 -*-
"""APP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V-qTFZmSOokF92f7ubpn5tiX9MmTq8m6
"""

with open("app.py", "w") as f:
    f.write("""from flask import Flask
import psutil

app = Flask(__name__)

@app.route("/")
def home():
    return "Student Monitoring System Running 🚀"

@app.route("/health")
def health():
    cpu = psutil.cpu_percent()
    memory = psutil.virtual_memory().percent
    return {"CPU": cpu, "Memory": memory, "Status": "OK"}

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000)
""")