# -*- coding: utf-8 -*-
"""monitor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15T5qUO3OHQsY47FUyAKN55Msc7cvIYPP
"""

with open("monitor.py", "w") as f:
    f.write("""import psutil
import time

while True:
    cpu = psutil.cpu_percent()
    mem = psutil.virtual_memory().percent

    print(f"CPU: {cpu}% | Memory: {mem}%")

    if cpu > 50:
        print("🚨 ALERT: HIGH CPU!")

    if mem > 50:
        print("🚨 ALERT: HIGH MEMORY!")

    time.sleep(2)
""")