# -*- coding: utf-8 -*-
"""readme.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N6TW7XC_poVCOwi4VyqN-oNDco_iTJBa
"""

with open("README.md", "w") as f:
    f.write("""# Monitoring and Alerting System

This project monitors CPU and memory and generates alerts.
""")