# -*- coding: utf-8 -*-
"""requirements.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JmQ1qATN4fo5FYcAlGyymDVmRjktFtVO
"""

with open("requirements.txt", "w") as f:
    f.write("""flask
psutil
""")

