# -*- coding: utf-8 -*-
"""test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1scMXgJb7pfuXeZlFbqUUcLiyPpkcMIpQ
"""

with open("test.py", "w") as f:
    f.write("""import unittest

class TestSystem(unittest.TestCase):
    def test_sample(self):
        self.assertEqual(2+2, 4)

if __name__ == "__main__":
    unittest.main()
""")

# requirements.txt
with open("requirements.txt", "w") as f:
    f.write("""flask
psutil
""")

